[package]
name = "nu_plugin_vi_sysclip"
version = "0.1.0"
edition = "2024"
authors = ["Chuyang Chen <chuyangchen2018@outlook.com>"]
license-file = "LICENSE"

[dependencies]
nu-plugin = "0.105.1"
nu-protocol = "0.105.1"
